orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
jobs:
  build-and-push-image:
    environment:
      IMAGE_NAME: trolleye/netrecon
    docker:
      - image: 'cimg/base:2023.04'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: echo "Starting to build docker image"
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build -f Dockerfile --tag $IMAGE_NAME:latest .
              docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-and-test:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build-and-push-image:
          context:
            - dockerhub
