version: 2.1
executors:
  docker-publisher:
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), se
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
workflows:
  version: 2
  build-and-test:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build-and-push-image:
          context:
            - dockerhub

jobs:
  build-and-push-image:
    machine: true
    resource_class: trolleyesecurity/prod
    environment:
      IMAGE_NAME: trolleye/netrecon
    steps:
      - checkout
      - run:
          command: echo "Starting to build docker image"
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker buildx build --push --platform linux/arm64/v8,linux/amd64 -f Dockerfile --tag $IMAGE_NAME:latest .
            docker image prune -fa
